###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_DATABASE=customgarage
            - MYSQL_USER=appuser1
            - MYSQL_PASSWORD=12345
        ports:
            - '44002:3306'

    api:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '44000:80'

    php-fpm:
        build: php-fpm/
        working_dir: /application
        volumes:
            - '.:/application'
            - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
